steps:
  - id: "data pipeline"
    name: "python:3.9"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt
        pip install --upgrade pip
        python data-pipeline/generate_fake_data.py
        python data-pipeline/upload_to_bigquery.py
        python data-pipeline/transform_data.py

options:
  logging: CLOUD_LOGGING_ONLY
