steps:
  # Set up Cloud SDK and fetch secrets from Secret Manager
  - name: "hashicorp/terraform:1.0.0" # Use the official Terraform image
    args: ["init"]
    dir: "infrastructure/"

  - name: "hashicorp/terraform:1.0.0" # Use the official Terraform image
    args: ["plan"]
    dir: "infrastructure/"

  - name: "hashicorp/terraform:1.0.0"
    args: ["apply", "-auto-approve"]
    dir: "infrastructure/"
