steps:
  - name: "python:3.9"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt
        python apache_beam_job/data_transformation_pipeline.py

options:
  logging: CLOUD_LOGGING_ONLY
